{% set name = "libcst" %}
{% set version = "1.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f729c37c9317126da9475bdd06a7208eb52fcbd180a6341648b45a56b4ba708b

build:
  number: 0
  script:
    - rm %BUILD_PREFIX%\\.cargo.win\\config  # [win]
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
    - setuptools_scm
    - wheel
  run:
    - python
    - pyyaml >=5.2  # [py<313]
    - pyyaml-ft >=8.0.0  # [py==313]
    - pyyaml >=6.0.3  # [py>313]
    - typing-extensions  # [py<310]

test:
  imports:
    - libcst
    - libcst._nodes
    - libcst._nodes.tests
    - libcst._parser
    - libcst._parser.conversions
    - libcst._parser.parso
    - libcst._parser.parso.pgen2
    - libcst._parser.parso.python
    - libcst._parser.parso.tests
    - libcst._parser.tests
    - libcst._parser.types
    - libcst._parser.types.tests
    - libcst.codegen
    - libcst.codegen.tests
    - libcst.codemod
    - libcst.codemod.commands
    - libcst.codemod.commands.tests
    - libcst.codemod.tests
    - libcst.codemod.visitors
    - libcst.codemod.visitors.tests
    - libcst.helpers
    - libcst.helpers.tests
    - libcst.matchers
    - libcst.matchers.tests
    - libcst.metadata
    - libcst.metadata.tests
    - libcst.testing
    - libcst.tests
  commands:
    - pip check
    - pytest --pyargs libcst.tests
  requires:
    - pip
    - pytest
    - hypothesis

about:
  home: https://github.com/Instagram/LibCST
  summary: A concrete syntax tree with AST-like properties for Python 3.5, 3.6, 3.7 and 3.8 programs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    A Concrete Syntax Tree (CST) parser and serializer library for Python
  doc_url: https://libcst.readthedocs.io
  dev_url: https://github.com/Instagram/LibCST

extra:
  recipe-maintainers:
    - nehaljwani
    - bollwyvl