{% set name = "libcst" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e80ecdbe3fa43b3793cae8fa0b07a985bd9a693edbe6e9d076f5422ecadbf0db
  patches:
    - 0001-Add-headerpad_max_install_names-to-linker-arguments.patch

build:
  number: 0
  skip: true  # [py<39]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
    - cd native/libcst && cargo-bundle-licenses --format yaml --output THIRDPARTY.yml


requirements:
    build:
    - patch        # [not win]
    - m2-patch    # [win]
    - python
    - setuptools
    - setuptools-rust
    - setuptools_scm
    - wheel
    - {{ compiler('rust') }}
    - {{ compiler('cxx') }}
    host:
    - python
    - pip
    - setuptools
    - setuptools-rust
    - wheel
    run:
    - typing_extensions >=3.7.4.2
    - typing_inspect >=0.4.0
    - python
    - pyyaml >=5.2

test:
  imports:
    - libcst
    - libcst._nodes
    - libcst._nodes.tests
    - libcst._parser
    - libcst._parser.conversions
    - libcst._parser.parso
    - libcst._parser.parso.pgen2
    - libcst._parser.parso.python
    - libcst._parser.parso.tests
    - libcst._parser.tests
    - libcst._parser.types
    - libcst._parser.types.tests
    - libcst.codegen
    - libcst.codegen.tests
    - libcst.codemod
    - libcst.codemod.commands
    - libcst.codemod.commands.tests
    - libcst.codemod.tests
    - libcst.codemod.visitors
    - libcst.codemod.visitors.tests
    - libcst.helpers
    - libcst.helpers.tests
    - libcst.matchers
    - libcst.matchers.tests
    - libcst.metadata
    - libcst.metadata.tests
    - libcst.testing
    - libcst.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Instagram/LibCST
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A concrete syntax tree with AST-like properties for Python 3.5, 3.6, 3.7 and 3.8 programs.
  doc_url: https://libcst.readthedocs.io/
  dev_url: https://github.com/Instagram/LibCST

extra:
  recipe-maintainers:
    - nehaljwani
    - bollwyvl
